name: Deploy main branch

on:
  push:
    branches:
      - '**' # matches every branch
      - '!main' # excludes main

jobs:
  deploy-dev:
    name: deploy development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - uses: bhowell2/github-substring-action
        id: three
        with:
          value: ${{ github.sha }}
          length_from_start: 5
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage steps.three.outputs.substring
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
